import PageHero from '@/components/PageHero';
import { getT } from '@/lib/i18n';
import { ExternalLink } from 'lucide-react';

type MediaItem={source:string;key:string;url:string;tag:'press'|'international'|'official'};
const items:MediaItem[]=[
{source:'Borna News',key:'borna',url:'https://www.borna.news/%D8%A8%D8%AE%D8%B4-%D9%88%D8%B1%D8%B2%D8%B4%DB%8C-7/1105396-%D8%B5%D8%AD%D8%A8%D8%AA-%D9%87%D8%A7%DB%8C-%D8%AC%D8%A7%D9%84%D8%A8-%D8%A7%D9%88%D9%84%DB%8C%D9%86-%D9%85%D8%AF%D8%A7%D9%84-%D8%A2%D9%88%D8%B1-%D9%81%DB%8C%D8%AA%D9%86%D8%B3-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86-%D8%AF%D8%B1-%D8%AC%D9%87%D8%A7%D9%86-%D8%A8%D8%A8%DB%8C%D9%86%DB%8C%D8%AF',tag:'press'},
{source:'Mizan News',key:'mizan',url:'https://www.mizan.news/fa/news/244703',tag:'press'},
{source:'Young Journalists Club',key:'yjc',url:'https://www.yjc.ir/fa/news/5866612',tag:'press'},
{source:'Borna / Vista',key:'vista',url:'https://vista.ir/n/borna-5ndxb',tag:'press'},
{source:'NPC News Online',key:'npc',url:'https://contests.npcnewsonline.com/contests/2017/arnold_amateur/4j45/hassan_golestaneh',tag:'international'},
{source:'GMV International',key:'gmv',url:'https://gmvimbb.com/2017-arnold-usa-results-amateur-men/',tag:'international'},
{source:'Fitness International Federation',key:'fif',url:'https://www.fifinternational.net/our-team',tag:'international'},
{source:'National Olympic Committee of Iran',key:'noc',url:'https://www.olympic.ir/Components/News/View/NewsPDF2.aspx?id=40557&lcid=1033',tag:'official'},
{source:'Fitness Academy Europe',key:'fae',url:'https://fitnessacademyeurope.com/faepro/user/fae995279/',tag:'official'},
{source:'Wikipedia',key:'wiki',url:'https://en.wikipedia.org/wiki/Hassan_Golestaneh',tag:'official'},
{source:'IMDb',key:'imdb',url:'https://www.imdb.com/name/nm13963676/',tag:'official'},
{source:'Instagram',key:'instagram',url:'https://www.instagram.com/mrsportmodel/',tag:'official'}];
const copy:Record<string,any>={
 en:{eyebrow:'PRESS / MEDIA',videoEyebrow:'COMPETITION FILM',videoTitle:'Huntington Beach · 2017',videoSub:'Fitness Sport · California, USA',featured:'Featured coverage',press:'News & Press',international:'International Coverage',official:'Official Profiles',read:'Open source',titles:{borna:'First Iranian world fitness medalist — interview and profile',mizan:'A historic Iranian presence in world fitness',yjc:'International fitness podium coverage',vista:'Sports leadership appointment',npc:'2017 Arnold Amateur — official competitor record',gmv:'2017 Arnold USA Amateur — results archive',fif:'FIF Iran President · FIF Armenia President',noc:'Official sports appointment — 2024',fae:'Fitness Nutrition Specialist profile',wiki:'Hassan Golestaneh — public biography',imdb:'Hassan Golestaneh — IMDb profile',instagram:'Official Instagram · @mrsportmodel'}},
 fa:{eyebrow:'رسانه / خبر',videoEyebrow:'ویدیوی مسابقه',videoTitle:'Huntington Beach · ۲۰۱۷',videoSub:'Fitness Sport · کالیفرنیا، آمریکا',featured:'پوشش‌های منتخب',press:'خبرها و رسانه‌ها',international:'پوشش بین‌المللی',official:'پروفایل‌های رسمی',read:'مشاهده منبع',titles:{borna:'گفت‌وگو و معرفی نخستین مدال‌آور جهانی فیتنس ایران',mizan:'حضور تاریخی ایران در فیتنس جهان',yjc:'پوشش سکوی بین‌المللی فیتنس',vista:'انتصاب ورزشی',npc:'Arnold Amateur 2017 — رکورد رسمی شرکت‌کننده',gmv:'Arnold USA Amateur 2017 — آرشیو نتایج',fif:'رئیس FIF ایران · رئیس FIF ارمنستان',noc:'انتصاب رسمی ورزشی — ۲۰۲۴',fae:'پروفایل Fitness Nutrition Specialist',wiki:'حسن گلستانه — زندگینامه عمومی',imdb:'حسن گلستانه — پروفایل IMDb',instagram:'اینستاگرام رسمی · @mrsportmodel'}},
 fr:{eyebrow:'PRESSE / MÉDIAS',videoEyebrow:'FILM DE COMPÉTITION',videoTitle:'Huntington Beach · 2017',videoSub:'Fitness Sport · Californie, États-Unis',featured:'Couverture à la une',press:'Actualités & Presse',international:'Couverture internationale',official:'Profils officiels',read:'Voir la source',titles:{borna:'Premier médaillé mondial iranien de fitness — entretien et profil',mizan:'Une présence iranienne historique dans le fitness mondial',yjc:'Couverture d’un podium international de fitness',vista:'Nomination sportive',npc:'Arnold Amateur 2017 — fiche officielle du compétiteur',gmv:'Arnold USA Amateur 2017 — archives des résultats',fif:'Président FIF Iran · Président FIF Arménie',noc:'Nomination sportive officielle — 2024',fae:'Profil Fitness Nutrition Specialist',wiki:'Hassan Golestaneh — biographie publique',imdb:'Hassan Golestaneh — profil IMDb',instagram:'Instagram officiel · @mrsportmodel'}},
 es:{eyebrow:'PRENSA / MEDIOS',videoEyebrow:'VIDEO DE COMPETICIÓN',videoTitle:'Huntington Beach · 2017',videoSub:'Fitness Sport · California, EE. UU.',featured:'Cobertura destacada',press:'Noticias y prensa',international:'Cobertura internacional',official:'Perfiles oficiales',read:'Abrir fuente',titles:{borna:'Primer medallista mundial iraní de fitness — entrevista y perfil',mizan:'Una presencia iraní histórica en el fitness mundial',yjc:'Cobertura de un podio internacional de fitness',vista:'Nombramiento deportivo',npc:'Arnold Amateur 2017 — registro oficial del competidor',gmv:'Arnold USA Amateur 2017 — archivo de resultados',fif:'Presidente FIF Irán · Presidente FIF Armenia',noc:'Nombramiento deportivo oficial — 2024',fae:'Perfil Fitness Nutrition Specialist',wiki:'Hassan Golestaneh — biografía pública',imdb:'Hassan Golestaneh — perfil IMDb',instagram:'Instagram oficial · @mrsportmodel'}}};
function Card({item,read,title}:{item:MediaItem;read:string;title:string}){return <a className="mediaCard" href={item.url} target="_blank" rel="noreferrer"><div><small>{item.source}</small><h2>{title}</h2></div><span>{read}<ExternalLink size={15}/></span></a>}
export default async function Media({params}:{params:Promise<{lang:string}>}){const {lang}=await params;const tr=getT(lang);const c=copy[lang]??copy.en;const featured=items.slice(0,3);const groups:[string,MediaItem[]][]=[[c.press,items.filter(x=>x.tag==='press')],[c.international,items.filter(x=>x.tag==='international')],[c.official,items.filter(x=>x.tag==='official')]];return <><PageHero eyebrow={c.eyebrow} title={tr.mediaTitle} lead={tr.mediaLead}/><section className="mediaFilm"><video autoPlay muted loop playsInline preload="metadata"><source src="/videos/events/huntington-2017.mp4" type="video/mp4"/></video><div className="mediaFilmShade"/><div className="mediaFilmCopy"><small>{c.videoEyebrow}</small><h2>{c.videoTitle}</h2><p>{c.videoSub}</p></div></section><section className="mediaHub"><div className="mediaSectionHead"><span>01</span><h2>{c.featured}</h2></div><div className="mediaFeatured">{featured.map(x=><Card key={x.url} item={x} read={c.read} title={c.titles[x.key]}/>)}</div>{groups.map(([title,list],i)=><section className="mediaGroup" key={title}><div className="mediaSectionHead"><span>0{i+2}</span><h2>{title}</h2></div><div className="mediaCards">{list.map(x=><Card key={x.url} item={x} read={c.read} title={c.titles[x.key]}/>)}</div></section>)}</section></>}
