export const locales = ['en','fa','fr','es'] as const;
export type Locale = typeof locales[number];

export const t = {
  en: {
    dir:'ltr', language:'EN', home:'Home', about:'Biography', career:'Career', achievements:'Achievements', media:'Media', gallery:'Gallery', contact:'Contact',
    heroEyebrow:'OFFICIAL WEBSITE', heroTitle:'HASSAN GOLESTANEH', heroSub:'Athlete · Fitness Medalist · Coach · Sports Figure', heroCta:'Discover the story',
    introTitle:'A life built through sport.', introBody:'Hassan Golestaneh has spent decades across competitive sport, fitness, coaching and sports development. This website brings together his story, milestones, public records and official links in one place.',
    pillars:['Competition','Coaching','Leadership','Legacy'],
    featuredTitle:'Selected milestones', featured:[
      ['2016','International fitness medal','Public biographies and Iranian sports coverage describe Golestaneh as the first Iranian world fitness medalist.'],
      ['2017','Arnold Amateur','Competitor record appears in the official NPC News Online archive for the 2017 Arnold Amateur.'],
      ['International','Coaching & judging','His public record includes national-team coaching, fitness judging and sports-development roles.']
    ],
    explore:'Explore', quote:'Sport is not a moment. It is a lifetime of discipline, responsibility and evolution.',
    aboutTitle:'Biography', aboutLead:'From football and martial arts to fitness, coaching and international competition.',
    aboutP1:'Golestaneh’s public biography traces his sporting path from youth football into bodybuilding, jujitsu and later professional fitness competition. His career expanded beyond competition into coaching, judging and sports administration.',
    aboutP2:'Independent and institutional references also document his visibility in Iranian fitness, international competition and professional education. This site is designed as a living archive: major claims are kept conservative and linked to public sources wherever possible.',
    careerTitle:'Career', careerLead:'A multidisciplinary sporting path.',
    careerItems:[['Youth','Football & early training','Began sport at a young age and later moved deeply into strength and physique training.'],['Development','Bodybuilding & martial arts','Built a long foundation in bodybuilding and practiced jujitsu for several years.'],['Coaching','National-team experience','Public biographies describe years of coaching athletes for international fitness competition.'],['Competition','International stage','Competed internationally, including the 2017 Arnold Amateur in the United States.'],['Leadership','Judging & sports roles','Expanded into judging, representation and sports-development positions.']],
    achievementsTitle:'Achievements', achievementsLead:'Selected publicly documented highlights.',
    achievementsItems:[['First Iranian world fitness medalist','This description appears repeatedly in public sports coverage and on his public biography.'],['2017 Arnold Amateur competitor','Official NPC News Online contest archive lists Hassan Golestaneh in the 2017 Arnold Amateur.'],['Fitness Nutrition Specialist','Fitness Academy Europe lists Hassan Golestaneh with the specialty Fitness Nutrition Specialist.'],['Sports leadership appointments','Iran’s National Olympic Committee published an English item in 2024 describing a woodball appointment and referring to him as Iran’s first world fitness medalist.']],
    mediaTitle:'Media & Official Links', mediaLead:'Public profiles, competition records and press references.',
    galleryTitle:'Gallery', galleryLead:'Competition, training, media and career moments.', galleryEmpty:'Add your selected official photos to public/images and replace these placeholders whenever you are ready.',
    contactTitle:'Contact', contactLead:'For media, professional collaborations and official enquiries.', contactText:'Use the official social links below. A dedicated contact email can be added here at any time.',
    footer:'Official website · Hassan Golestaneh'
  },
  fa: {
    dir:'rtl', language:'فارسی', home:'خانه', about:'زندگینامه', career:'مسیر حرفه‌ای', achievements:'افتخارات', media:'رسانه', gallery:'گالری', contact:'تماس',
    heroEyebrow:'وب‌سایت رسمی', heroTitle:'حسن گلستانه', heroSub:'ورزشکار · مدال‌آور فیتنس · مربی · چهره ورزشی', heroCta:'مشاهده مسیر زندگی',
    introTitle:'زندگی‌ای ساخته‌شده با ورزش.', introBody:'حسن گلستانه چند دهه در ورزش رقابتی، فیتنس، مربیگری و توسعه ورزش فعالیت داشته است. این وب‌سایت داستان، نقاط عطف، سوابق عمومی و لینک‌های رسمی او را در یک مرجع واحد گردآوری می‌کند.',
    pillars:['مسابقه','مربیگری','مدیریت','میراث ورزشی'],
    featuredTitle:'برخی نقاط عطف', featured:[['۲۰۱۶','مدال بین‌المللی فیتنس','زندگینامه‌های عمومی و رسانه‌های ورزشی ایران از گلستانه به‌عنوان نخستین مدال‌آور جهانی فیتنس ایران یاد کرده‌اند.'],['۲۰۱۷','Arnold Amateur','نام او در آرشیو رسمی NPC News Online برای مسابقات Arnold Amateur سال ۲۰۱۷ ثبت شده است.'],['بین‌المللی','مربیگری و داوری','سوابق عمومی او شامل مربیگری تیم، داوری فیتنس و نقش‌های توسعه ورزشی است.']],
    explore:'بیشتر', quote:'ورزش یک لحظه نیست؛ یک عمر انضباط، مسئولیت و رشد است.',
    aboutTitle:'زندگینامه', aboutLead:'از فوتبال و هنرهای رزمی تا فیتنس، مربیگری و رقابت بین‌المللی.',
    aboutP1:'زندگینامه عمومی گلستانه مسیر ورزشی او را از فوتبال در نوجوانی به بدنسازی، جوجیتسو و سپس رقابت حرفه‌ای فیتنس دنبال می‌کند. فعالیت او بعدتر از مسابقه فراتر رفت و مربیگری، داوری و مسئولیت‌های مدیریتی ورزشی را نیز دربر گرفت.',
    aboutP2:'منابع مستقل و سازمانی نیز حضور او در فیتنس ایران، مسابقات بین‌المللی و آموزش حرفه‌ای را ثبت کرده‌اند. این وب‌سایت به‌عنوان یک آرشیو زنده طراحی شده و ادعاهای مهم تا حد ممکن محافظه‌کارانه و متکی بر منابع عمومی نگه داشته می‌شوند.',
    careerTitle:'مسیر حرفه‌ای', careerLead:'یک مسیر چندرشته‌ای در ورزش.', careerItems:[['آغاز','فوتبال و تمرینات اولیه','ورزش را از سن پایین آغاز کرد و سپس به‌طور جدی وارد تمرینات قدرتی و فیزیک شد.'],['توسعه','بدنسازی و هنرهای رزمی','سال‌ها در بدنسازی فعالیت کرد و چندین سال نیز جوجیتسو تمرین کرد.'],['مربیگری','تجربه تیمی','زندگینامه‌های عمومی از سال‌ها مربیگری ورزشکاران برای مسابقات بین‌المللی فیتنس یاد می‌کنند.'],['مسابقات','حضور بین‌المللی','در مسابقات بین‌المللی از جمله Arnold Amateur 2017 در آمریکا حضور داشت.'],['مدیریت','داوری و نقش‌های ورزشی','فعالیت او به داوری، نمایندگی و مسئولیت‌های توسعه ورزش نیز گسترش یافت.']],
    achievementsTitle:'افتخارات', achievementsLead:'منتخبی از موارد دارای سابقه عمومی.', achievementsItems:[['نخستین مدال‌آور جهانی فیتنس ایران','این عنوان در چند منبع ورزشی و زندگینامه عمومی او تکرار شده است.'],['شرکت‌کننده Arnold Amateur 2017','آرشیو رسمی NPC News Online نام Hassan Golestaneh را در مسابقات ۲۰۱۷ ثبت کرده است.'],['Fitness Nutrition Specialist','Fitness Academy Europe تخصص Fitness Nutrition Specialist را برای Hassan Golestaneh درج کرده است.'],['سمت‌های ورزشی','کمیته ملی المپیک ایران در سال ۲۰۲۴ مطلب انگلیسی درباره انتصاب او در وودبال منتشر کرده و از او به‌عنوان نخستین مدال‌آور جهانی فیتنس ایران نام برده است.']],
    mediaTitle:'رسانه و لینک‌های رسمی', mediaLead:'پروفایل‌های عمومی، سوابق مسابقات و منابع خبری.',
    galleryTitle:'گالری', galleryLead:'مسابقات، تمرین، رسانه و لحظات مسیر حرفه‌ای.', galleryEmpty:'هر زمان آماده بودی عکس‌های رسمی انتخابی خودت را داخل public/images قرار می‌دهیم و این بخش را کامل می‌کنیم.',
    contactTitle:'تماس', contactLead:'برای رسانه، همکاری حرفه‌ای و درخواست‌های رسمی.', contactText:'در حال حاضر از لینک‌های رسمی شبکه‌های اجتماعی استفاده کن. ایمیل اختصاصی تماس را هر زمان بخواهی می‌توانیم اضافه کنیم.',
    footer:'وب‌سایت رسمی · حسن گلستانه'
  },
  fr: {
    dir:'ltr', language:'FR', home:'Accueil', about:'Biographie', career:'Carrière', achievements:'Palmarès', media:'Médias', gallery:'Galerie', contact:'Contact',
    heroEyebrow:'SITE OFFICIEL', heroTitle:'HASSAN GOLESTANEH', heroSub:'Athlète · Médaillé fitness · Entraîneur · Figure sportive', heroCta:'Découvrir le parcours',
    introTitle:'Une vie construite par le sport.', introBody:'Hassan Golestaneh a consacré plusieurs décennies au sport de compétition, au fitness, à l’entraînement et au développement sportif. Ce site réunit son parcours, ses étapes majeures, ses archives publiques et ses liens officiels.',
    pillars:['Compétition','Coaching','Leadership','Héritage'], featuredTitle:'Repères sélectionnés', featured:[['2016','Médaille internationale de fitness','Des biographies publiques et médias sportifs iraniens le décrivent comme le premier médaillé mondial iranien de fitness.'],['2017','Arnold Amateur','Son nom figure dans l’archive officielle NPC News Online de l’Arnold Amateur 2017.'],['International','Coaching et jugement','Son parcours public comprend le coaching, le jugement en fitness et des fonctions de développement sportif.']],
    explore:'Découvrir', quote:'Le sport n’est pas un moment. C’est une vie de discipline, de responsabilité et d’évolution.',
    aboutTitle:'Biographie', aboutLead:'Du football et des arts martiaux au fitness, au coaching et à la compétition internationale.', aboutP1:'Sa biographie publique retrace un parcours allant du football de jeunesse à la musculation, au jujitsu puis à la compétition de fitness. Sa carrière s’est ensuite élargie au coaching, au jugement et à l’administration sportive.', aboutP2:'Des sources indépendantes et institutionnelles documentent également sa présence dans le fitness iranien, la compétition internationale et la formation professionnelle. Ce site est conçu comme une archive évolutive, avec des affirmations formulées prudemment et reliées autant que possible à des sources publiques.',
    careerTitle:'Carrière', careerLead:'Un parcours sportif multidisciplinaire.', careerItems:[['Jeunesse','Football et premiers entraînements','Débuts sportifs précoces avant un engagement profond dans la force et le physique.'],['Développement','Musculation et arts martiaux','Longue base en musculation et plusieurs années de jujitsu.'],['Coaching','Expérience d’équipe','Les biographies publiques décrivent plusieurs années de préparation d’athlètes pour des compétitions internationales.'],['Compétition','Scène internationale','Participation à des événements internationaux, dont l’Arnold Amateur 2017 aux États-Unis.'],['Leadership','Jugement et fonctions sportives','Évolution vers le jugement, la représentation et des responsabilités de développement sportif.']],
    achievementsTitle:'Palmarès', achievementsLead:'Sélection d’éléments publiquement documentés.', achievementsItems:[['Premier médaillé mondial iranien de fitness','Cette formulation apparaît à plusieurs reprises dans la presse sportive et sa biographie publique.'],['Participant Arnold Amateur 2017','L’archive officielle NPC News Online répertorie Hassan Golestaneh pour l’Arnold Amateur 2017.'],['Fitness Nutrition Specialist','Fitness Academy Europe répertorie Hassan Golestaneh avec la spécialité Fitness Nutrition Specialist.'],['Fonctions sportives','Le Comité National Olympique iranien a publié en 2024 un article en anglais relatif à une nomination en woodball et le présente comme premier médaillé mondial iranien de fitness.']],
    mediaTitle:'Médias & Liens officiels', mediaLead:'Profils publics, archives de compétition et références presse.', galleryTitle:'Galerie', galleryLead:'Compétition, entraînement, médias et moments de carrière.', galleryEmpty:'Ajoutez vos photos officielles dans public/images lorsque vous serez prêt.', contactTitle:'Contact', contactLead:'Pour les médias, collaborations professionnelles et demandes officielles.', contactText:'Utilisez les liens sociaux officiels ci-dessous. Une adresse e-mail dédiée pourra être ajoutée à tout moment.', footer:'Site officiel · Hassan Golestaneh'
  },
  es: {
    dir:'ltr', language:'ES', home:'Inicio', about:'Biografía', career:'Carrera', achievements:'Logros', media:'Medios', gallery:'Galería', contact:'Contacto',
    heroEyebrow:'SITIO OFICIAL', heroTitle:'HASSAN GOLESTANEH', heroSub:'Atleta · Medallista de fitness · Entrenador · Figura deportiva', heroCta:'Descubrir la historia',
    introTitle:'Una vida construida a través del deporte.', introBody:'Hassan Golestaneh ha dedicado décadas al deporte competitivo, el fitness, el entrenamiento y el desarrollo deportivo. Este sitio reúne su historia, hitos, registros públicos y enlaces oficiales.', pillars:['Competición','Coaching','Liderazgo','Legado'], featuredTitle:'Hitos seleccionados', featured:[['2016','Medalla internacional de fitness','Biografías públicas y prensa deportiva iraní lo describen como el primer medallista mundial iraní de fitness.'],['2017','Arnold Amateur','Su registro aparece en el archivo oficial de NPC News Online del Arnold Amateur 2017.'],['Internacional','Coaching y juzgamiento','Su trayectoria pública incluye entrenamiento, juzgamiento de fitness y funciones de desarrollo deportivo.']], explore:'Explorar', quote:'El deporte no es un momento. Es una vida de disciplina, responsabilidad y evolución.',
    aboutTitle:'Biografía', aboutLead:'Del fútbol y las artes marciales al fitness, el coaching y la competición internacional.', aboutP1:'Su biografía pública sigue un recorrido desde el fútbol juvenil hacia el culturismo, el jujitsu y posteriormente la competición profesional de fitness. Su carrera se amplió después al coaching, el juzgamiento y la administración deportiva.', aboutP2:'Fuentes independientes e institucionales también documentan su presencia en el fitness iraní, la competición internacional y la formación profesional. Este sitio funciona como un archivo vivo, con afirmaciones importantes formuladas con prudencia y vinculadas a fuentes públicas siempre que es posible.',
    careerTitle:'Carrera', careerLead:'Una trayectoria deportiva multidisciplinaria.', careerItems:[['Juventud','Fútbol y entrenamiento inicial','Comenzó a practicar deporte desde joven y después se centró intensamente en fuerza y físico.'],['Desarrollo','Culturismo y artes marciales','Construyó una larga base en culturismo y practicó jujitsu durante varios años.'],['Coaching','Experiencia de equipo','Biografías públicas describen años entrenando atletas para competiciones internacionales de fitness.'],['Competición','Escenario internacional','Compitió internacionalmente, incluido el Arnold Amateur 2017 en Estados Unidos.'],['Liderazgo','Juzgamiento y funciones deportivas','Su carrera se amplió al juzgamiento, representación y desarrollo deportivo.']],
    achievementsTitle:'Logros', achievementsLead:'Selección de hitos documentados públicamente.', achievementsItems:[['Primer medallista mundial iraní de fitness','Esta descripción aparece de forma repetida en prensa deportiva y en su biografía pública.'],['Competidor Arnold Amateur 2017','El archivo oficial de NPC News Online incluye a Hassan Golestaneh en el Arnold Amateur 2017.'],['Fitness Nutrition Specialist','Fitness Academy Europe lista a Hassan Golestaneh con la especialidad Fitness Nutrition Specialist.'],['Nombramientos deportivos','El Comité Olímpico Nacional de Irán publicó en 2024 una nota en inglés sobre un nombramiento en woodball y lo describió como el primer medallista mundial iraní de fitness.']],
    mediaTitle:'Medios y enlaces oficiales', mediaLead:'Perfiles públicos, registros de competición y referencias de prensa.', galleryTitle:'Galería', galleryLead:'Competición, entrenamiento, medios y momentos de carrera.', galleryEmpty:'Añade tus fotos oficiales a public/images cuando quieras completar esta sección.', contactTitle:'Contacto', contactLead:'Para medios, colaboraciones profesionales y consultas oficiales.', contactText:'Usa los enlaces sociales oficiales. Podemos añadir un correo de contacto dedicado en cualquier momento.', footer:'Sitio oficial · Hassan Golestaneh'
  }
} as const;

export function getT(lang:string){ return (t as any)[lang] ?? t.en; }
