import type { Metadata } from 'next';
import { pageMetadata } from '@/lib/seo';
import PageHero from '@/components/PageHero'; import {getT} from '@/lib/i18n';
const copy:Record<string,any>={
 en:{lead:'More than two decades across modern fitness, international competition, coaching and judging.',items:[['01','Professional foundation','More than twenty years of professional activity in modern fitness and athlete development.'],['02','International competition','A competitive career that includes world-level events in Ireland and the United States.'],['03','Coaching','International coaching and athlete preparation across fitness disciplines.'],['04','Judging','Experience as an international fitness judge and in competition environments.'],['05','Development','A role in introducing and promoting modern fitness disciplines in Iran, alongside sports-development projects.'],['06','Media & global work','A body of work covered by sports media, with current focus on international projects, media and global sports development.']]},
 fa:{lead:'بیش از دو دهه فعالیت در فیتنس مدرن، رقابت بین‌المللی، مربی‌گری و داوری.',items:[['۰۱','پایه حرفه‌ای','بیش از بیست سال فعالیت حرفه‌ای در فیتنس مدرن و آماده‌سازی ورزشکاران.'],['۰۲','رقابت بین‌المللی','مسیر رقابتی شامل حضور در رویدادهای جهانی در ایرلند و ایالات متحده.'],['۰۳','مربی‌گری','مربی‌گری بین‌المللی و آماده‌سازی ورزشکاران در رشته‌های فیتنس.'],['۰۴','داوری','سابقه داوری بین‌المللی فیتنس و فعالیت در محیط مسابقات.'],['۰۵','توسعه ورزش','نقش در معرفی و ترویج رشته‌های نوین فیتنس در ایران و مشارکت در پروژه‌های توسعه ورزش.'],['۰۶','رسانه و فعالیت جهانی','فعالیت‌هایی که توسط رسانه‌های ورزشی پوشش داده شده و امروز بر پروژه‌های بین‌المللی، رسانه‌ای و توسعه ورزش در سطح جهانی متمرکز است.']]},
 fr:{lead:'Plus de deux décennies dans le fitness moderne, la compétition internationale, le coaching et le jugement.',items:[['01','Fondation professionnelle','Plus de vingt ans d’activité professionnelle dans le fitness moderne et la préparation des athlètes.'],['02','Compétition internationale','Un parcours comprenant des événements mondiaux en Irlande et aux États-Unis.'],['03','Coaching','Coaching international et préparation d’athlètes dans plusieurs disciplines du fitness.'],['04','Jugement','Expérience comme juge international de fitness et dans l’environnement des compétitions.'],['05','Développement','Un rôle dans l’introduction et la promotion de disciplines modernes du fitness en Iran et dans des projets de développement sportif.'],['06','Médias & international','Un parcours couvert par les médias sportifs, aujourd’hui orienté vers les projets internationaux, les médias et le développement du sport.']]},
 es:{lead:'Más de dos décadas en fitness moderno, competición internacional, entrenamiento y juzgamiento.',items:[['01','Base profesional','Más de veinte años de actividad profesional en fitness moderno y preparación de atletas.'],['02','Competición internacional','Una trayectoria que incluye eventos de nivel mundial en Irlanda y Estados Unidos.'],['03','Entrenamiento','Coaching internacional y preparación de atletas en distintas disciplinas de fitness.'],['04','Juzgamiento','Experiencia como juez internacional de fitness y en entornos competitivos.'],['05','Desarrollo','Un papel en la introducción y promoción de disciplinas modernas de fitness en Irán y en proyectos de desarrollo deportivo.'],['06','Medios y trabajo global','Una trayectoria cubierta por medios deportivos, con enfoque actual en proyectos internacionales, medios y desarrollo deportivo global.']]}};

export async function generateMetadata({params}:{params:Promise<{lang:string}>}):Promise<Metadata>{ const {lang}=await params; return pageMetadata(lang,'career','career'); }
export default async function Career({params}:{params:Promise<{lang:string}>}){const {lang}=await params;const tr=getT(lang);const c=copy[lang]??copy.en;return <><PageHero eyebrow="JOURNEY" title={tr.careerTitle} lead={c.lead}/><section className="timeline">{c.items.map((x:any)=><article key={x[0]}><span className="index">{x[0]}</span><div><small>{tr.career}</small><h2>{x[1]}</h2><p>{x[2]}</p></div></article>)}</section></>}
